### PR TITLE
Update to version 2.0.0, update recipe

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Requires gcc7 label for r-pillar ... mentioned here https://github.com/conda-forge/conda-forge.github.io/issues/674

**Comment by bgruening** [comment]
relabled and restarted

**Comment by dbast** [comment]
Thanks!

**Comment by dbast** [comment]
Ok, ready it is :)

**Pull request merged**
